plugins {
  id 'maven-publish'
  id 'net.neoforged.moddev' version '2.0.126'
}

base {
  archivesName = "${project.mod_id}-common-${project.minecraft_version}"
}

neoForge {
  neoFormVersion = neo_form_version
}

dependencies {
  // Include Core Common code
  compileOnly("de.markusbordihn.easynpc:easy_npc-common-${project.minecraft_version}:${project.version}") {
    changing = true
  }
}

processResources {
  def buildProps = project.properties.clone()

  filesMatching(['pack.mcmeta']) {
    expand buildProps
  }
}

tasks.register("prepareWorkspace") {
  group = "ide"
  description = "Runs post-sync tasks for IDE integration"
}
