modLoader = "javafml"
loaderVersion = "[5,)"
license = "MIT"
issueTrackerURL = "https://github.com/MarkusBordihn/BOs-Easy-NPC/issues"

[[mods]]
modId = "easy_npc_config_ui"
version = "${file.jarVersion}"
displayName = "Easy NPC: Config UI"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/easy-npc"
logoFile = "logo.png"
credits = ""
authors = "Markus Bordihn"
description = '''Create easily NPCs for your world or for your mods.'''

[[dependencies.easy_npc_config_ui]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.easy_npc_config_ui]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,26.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.easy_npc_config_ui]]
modId = "easy_npc"
type = "required"
versionRange = "[${file.jarVersion},${file.nextMajorVersion})"
ordering = "AFTER"
side = "BOTH"

[[dependencies.easy_npc_config_ui]]
modId = "easy_model_entities"
type = "optional"
versionRange = "[2.2.0,3.0.0)"
ordering = "AFTER"
side = "BOTH"
