plugins {
  id 'maven-publish'
  id 'net.neoforged.moddev' version '2.0.72'
}

archivesBaseName = "${project.mod_id}-common-${project.minecraft_version}"

neoForge {
  neoFormVersion = neo_form_version
}

dependencies {
  compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.7'
}

apply from: "$projectDir/../gradle/tasks/generateRawNPCs.gradle"

publishing {
  publications {
    mavenJava(MavenPublication) {
      groupId project.group
      artifactId project.archivesBaseName
      version project.version
      artifact jar
    }
  }
}

tasks.named('build') {
  finalizedBy tasks.named('publishToMavenLocal')
}
