plugins {
  id 'idea'
  id "org.jetbrains.gradle.plugin.idea-ext" version "1.1.8"
}

tasks.register('runAllGameTests') {
  group = 'verification'
  description = 'Runs both Fabric and Forge game tests.'
  if (rootProject.findProject(":core")) {
    dependsOn ':core:Fabric:runGameTest', ':core:Forge:runGameTestServer', ':core:NeoForge:runGameTestServer'
  } else {
    dependsOn ':Fabric:runGameTest', ':Forge:runGameTestServer', ':NeoForge:runGameTestServer'
  }
}

subprojects {

  apply plugin: 'java'

  repositories {
    mavenCentral()
    maven {
      url "https://www.cursemaven.com"
      content {
        includeGroup "curse.maven"
      }
    }
  }

  dependencies {
    configurations.configureEach {
      resolutionStrategy.force 'org.ow2.asm:asm-analysis:9.7'
      resolutionStrategy.force 'org.ow2.asm:asm-util:9.7'
    }
  }

  idea {
    module {
      downloadSources = true
      downloadJavadoc = true
    }
  }

}
