# Gradle Settings
org.gradle.jvmargs=-Xmx4G -XX:+UseParallelGC -XX:MaxMetaspaceSize=1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
fabric.loom.multiProjectOptimisation=true
# Project
version=7.5.0
group=de.markusbordihn.easynpc
vendor_name=markusbordihn
# Mod
mod_id=easy_npc
mod_name=Easy NPC
mod_author=Markus Bordihn
mod_namespace=easynpc
# Common
minecraft_version=1.20.1
# Easy Model Entities
easy_model_entities_version=1.6.0
# Forge Mod Loader
forge_version=47.4.10
# Forge Helper Mods (Modrinth / Xaero maven versions)
forge_jei_version=15.21.0.138-forge
forge_xaeros_minimap_version=26.4.2
forge_xaerolib_version=1.7.1
forge_easy_model_entities_version=1.7.0-forge
forge_epic_fight_version=20.14.17-mc1.20.1-forge
forge_cobblemon_version=1.5.2-forge
forge_kotlin_for_forge_version=4.12.0
forge_architectury_version=9.2.14+forge
# Fabric Mod Loader
fabric_version=0.92.6+1.20.1
fabric_loader_version=0.18.3
fabric_loom=1.9-SNAPSHOT
# Fabric Helper Mods (Modrinth / Xaero maven versions)
fabric_jei_version=15.21.0.138-fabric
fabric_xaeros_minimap_version=26.4.2
fabric_xaerolib_version=1.7.1
fabric_easy_model_entities_version=1.7.0-fabric
fabric_cobblemon_version=1.5.2-fabric
# Publish to CurseForge
curseforge_release_type=release
curseforge_project_id=1308987
curseforge_api_token=Never put your token here!
# Publish to Modrinth
modrinth_release_type=release
modrinth_project_id=Epm6R3P2
modrinth_api_token=Never put your token here!
