# Gradle Settings
org.gradle.jvmargs=-Xmx4G -XX:+UseParallelGC -XX:MaxMetaspaceSize=1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
fabric.loom.multiProjectOptimisation=true
# Project
version=7.0.1
group=de.markusbordihn.easynpc
vendor_name=markusbordihn
# Mod
mod_id=easy_npc
mod_name=Easy NPC
mod_author=Markus Bordihn
mod_namespace=easynpc
# Common
minecraft_version=26.1.2
neo_form_version=26.1.2-1
# Easy Model Entities
easy_model_entities_version=1.5.1
# Forge Mod Loader
forge_version=64.0.11
# Forge Helper Mods
forge_jei_mod=
forge_xaeros_minimap_mod=
forge_easy_model_entities_mod=8412700
# Fabric Mod Loader
fabric_version=0.154.2+26.1.2
fabric_loader_version=0.19.2
fabric_loom=1.16-SNAPSHOT
# Fabric Helper Mods
fabric_jei_mod=
fabric_xaeros_minimap_mod=
fabric_easy_model_entities_mod=8412698
# NeoForge Mod Loader
neoforge_version=26.1.2.78
# NeoForge Helper Mods
neoforge_jei_mod=
neoforge_xaeros_minimap_mod=
neoforge_easy_model_entities_mod=8412699
# Publish to CurseForge
curseforge_release_type=release
curseforge_project_id=1308987
curseforge_api_token=Never put your token here!
# Publish to Modrinth
modrinth_release_type=release
modrinth_project_id=Epm6R3P2
modrinth_api_token=Never put your token here!
