# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m
org.gradle.daemon=false
org.gradle.caching=true
# Project
version=5.9.0
group=de.markusbordihn.easynpc
vendor_name=markusbordihn
# Common
minecraft_version=1.21.1
# Mod
mod_id=easy_npc
mod_name=Easy NPC
mod_author=Markus Bordihn
mod_namespace=easynpc
# Forge Mod Loader
forge_version=52.0.37
# Forge Helper Mods
forge_jei_mod=5846879
# forge_xaeros_minimap_mod=6012853 // Broken with GameTests
# Fabric Mod Loader
fabric_version=0.110.0+1.21.1
fabric_loader_version=0.16.9
fabric_loom=1.9-SNAPSHOT
# Fabric Helper Mods
fabric_jei_mod=5846878
fabric_xaeros_minimap_mod=6012856
# NeoForge Mod Loader
neoforge_version=21.1.93
# NeoForge Helper Mods
neoforge_jei_mod=5846880
neoforge_xaeros_minimap_mod=6012855
# CurseForge
curseforge_release_type=release
curseforge_project_id=559312
curseforge_api_token=Never put your token here!
# Modrinth
modrinth_release_type=release
modrinth_project_id=CgGEe1h3
modrinth_api_token=Never put your token here!
