plugins {
  id 'maven-publish'
  id 'net.fabricmc.fabric-loom' version "${fabric_loom}"
  id 'net.darkhax.curseforgegradle' version '1.2.30'
  id 'nu.studer.credentials' version '3.0'
  id "com.modrinth.minotaur" version "2.+"
}

base {
  archivesName = "${project.mod_id}-fabric-${project.minecraft_version}"
}

ext {
  getNextMajorVersion = { String currentVersion ->
    def versionParts = currentVersion.tokenize('.')
    if (versionParts.size() > 0) {
      def majorVersion = versionParts[0].toInteger()
      return "${majorVersion + 1}.0.0"
    }
    return "1.0.0"
  }
}

def nextMajorVersion = getNextMajorVersion(project.version.toString())

loom {
  accessWidenerPath = file("src/main/resources/easynpcconfig.accesswidener")
  runs {
    client {
      client()
      setConfigName("Fabric Client")
      property("fabric.logging.markers", "REGISTRIES")
      property("fabric.log.level", "debug")
      property("mixin.debug.verbose", "false")
      property("mixin.debug.export", "false")
      ideConfigGenerated(true)
      runDir("run")
    }
    server {
      server()
      setConfigName("Fabric Server")
      property("fabric.logging.markers", "REGISTRIES")
      property("fabric.log.level", "debug")
      property("mixin.debug.verbose", "false")
      property("mixin.debug.export", "false")
      ideConfigGenerated(true)
      runDir("run")
    }
    gameTest {
      server()
      name "Game Test"
      vmArg "-Dfabric-api.gametest"
    }
  }
}

dependencies {
  minecraft "com.mojang:minecraft:${minecraft_version}"
  implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
  implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

  // Include Common code
  implementation project(":Common")

  // Include Core Common code
  implementation("de.markusbordihn.easynpc:easy_npc-fabric-${project.minecraft_version}:${project.version}")
  runtimeOnly("de.markusbordihn.easynpc:easy_npc-fabric-${project.minecraft_version}:${project.version}")

  // Test dependencies
  testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.1'
  testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.1'
  testImplementation 'org.junit.jupiter:junit-jupiter-params:5.10.1'

  // Additional helpful Mods for development (runtime dependency)
  if (project.hasProperty('fabric_jei_mod') && project.fabric_jei_mod) {
    runtimeOnly("curse.maven:jei-238222:${project.fabric_jei_mod}")
  }
  if (project.hasProperty('fabric_xaeros_minimap_mod') && project.fabric_xaeros_minimap_mod) {
    runtimeOnly("curse.maven:xaeros_minimap-263420:${project.fabric_xaeros_minimap_mod}")
  }
}

tasks.withType(JavaCompile).configureEach {
  source(project(":Common").sourceSets.main.allSource)
}

processResources {
  from project(":Common").sourceSets.main.resources
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE

  inputs.property "version", project.version
  inputs.property 'nextMajorVersion', nextMajorVersion

  filesMatching("fabric.mod.json") {
    expand "version": project.version,
        "nextMajorVersion": nextMajorVersion
  }
}

tasks.withType(Test).configureEach {
  failOnNoDiscoveredTests = false
}

publishing {
  publications {
    mavenJava(MavenPublication) {
      groupId project.group
      artifactId base.archivesName.get()
      version project.version
      from components.java
    }
  }
}

tasks.named('build') {
  finalizedBy tasks.named('publishToMavenLocal')
}

// CurseForge Publishing
if (project.hasProperty('curseforge_project_id') && project.curseforge_project_id) {
  tasks.register('curseforge', net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    group = 'publishing'
    description = 'Uploads to CurseForge'
    apiToken = "${credentials.forKey('curseforge_api_token')}"

    def mainFile = upload(project.curseforge_project_id, jar)
    mainFile.changelogType = 'markdown'
    mainFile.changelog = rootProject.file("../CHANGELOG.md").text
    mainFile.releaseType = "${project.curseforge_release_type}"
    mainFile.addModLoader('Fabric')
    mainFile.addModLoader('Quilt')
    mainFile.addGameVersion("${project.minecraft_version}")
    mainFile.addRequirement('easy-npc-core')
  }
}

// Modrinth Publishing
if (project.hasProperty('modrinth_project_id') && project.modrinth_project_id) {
  modrinth {
    token = "${credentials.forKey('modrinth_api_token')}"
    projectId = "${project.modrinth_project_id}"
    versionNumber = "${version}"
    versionType = "${project.modrinth_release_type}"
    versionName = "${project.mod_name} ${project.version}"
    changelog = rootProject.file("../CHANGELOG.md").text
    uploadFile = jar
    gameVersions = ["${minecraft_version}"]
    loaders = ["fabric", "quilt"]
    dependencies {
      required.project "easy-npc-core"
    }
  }
}
