# Gradle Settings
org.gradle.jvmargs=-Xmx4G -XX:+UseParallelGC -XX:MaxMetaspaceSize=1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
fabric.loom.multiProjectOptimisation=true
# Project
version=7.9.0
group=de.markusbordihn.easynpc.bundle
vendor_name=markusbordihn
# Mod
mod_id=easy_npc_bundle
mod_name=Easy NPC (Bundle)
mod_author=Markus Bordihn
mod_namespace=easynpcbundle
# Common
minecraft_version=1.21.1
# Easy Model Entities
easy_model_entities_version=2.3.0
# Forge Mod Loader
forge_version=52.1.16
# Forge Helper Mods (Modrinth versions)
forge_easy_model_entities_version=gIt54DmX
# Fabric Mod Loader
fabric_version=0.116.14+1.21.1
fabric_loader_version=0.19.3
fabric_loom=1.9-SNAPSHOT
# Fabric Helper Mods (Modrinth versions)
fabric_easy_model_entities_version=VzSx0phX
# NeoForge Mod Loader
neoforge_version=21.1.244
# NeoForge Helper Mods (Modrinth versions)
neoforge_easy_model_entities_version=mNZXD111
# Publish to CurseForge
curseforge_release_type=release
curseforge_project_id=559312
curseforge_api_token=Never put your token here!
# Publish to Modrinth
modrinth_release_type=release
modrinth_project_id=CgGEe1h3
modrinth_api_token=Never put your token here!
