# Gradle Settings
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
fabric.loom.multiProjectOptimisation=true
# Project
version=6.1.2
group=de.markusbordihn.easynpc.configui
vendor_name=markusbordihn
# Mod
mod_id=easy_npc_config_ui
mod_name=Easy NPC Config UI
mod_author=Markus Bordihn
mod_namespace=easynpcconfigui
# Common
minecraft_version=1.21.5
neo_form_version=1.21.5-20250325.162830
# Forge Mod Loader
forge_version=55.0.15
# Forge Helper Mods
# forge_jei_mod=5846879
# forge_xaeros_minimap_mod=6012853 // Broken with GameTests
# Fabric Mod Loader
fabric_version=0.124.0+1.21.5
fabric_loader_version=0.17.2
fabric_loom=1.11-SNAPSHOT
# Fabric Helper Mods
# fabric_jei_mod=5846878
# fabric_xaeros_minimap_mod=6012856
# NeoForge Mod Loader
neoforge_version=21.5.95
# NeoForge Helper Mods
# neoforge_jei_mod=5846880
# neoforge_xaeros_minimap_mod=6012855
# Publish to CurseForge
curseforge_release_type=beta
curseforge_project_id=1214728
curseforge_api_token=Never put your token here!
# Publish to Modrinth
modrinth_release_type=beta
modrinth_project_id=uTGjf7vA
modrinth_api_token=Never put your token here!
