# Gradle Settings
org.gradle.jvmargs=-Xmx4G -XX:+UseParallelGC -XX:MaxMetaspaceSize=1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
fabric.loom.multiProjectOptimisation=true
# Project
version=7.10.0
group=de.markusbordihn.easynpc.configui
vendor_name=markusbordihn
# Mod
mod_id=easy_npc_config_ui
mod_name=Easy NPC Config UI
mod_author=Markus Bordihn
mod_namespace=easynpcconfigui
# Common
minecraft_version=1.21.1
neo_form_version=1.21.1-20240808.144430
# Easy Model Entities
easy_model_entities_version=2.3.0
# Forge Mod Loader
forge_version=52.1.16
# Forge Helper Mods (Modrinth / Xaero maven versions)
forge_jei_version=19.42.0.379-forge
forge_xaeros_minimap_version=26.4.2
forge_xaerolib_version=1.7.1
forge_easy_model_entities_version=gIt54DmX
# Fabric Mod Loader
fabric_version=0.116.14+1.21.1
fabric_loader_version=0.19.3
fabric_loom=1.9-SNAPSHOT
# Fabric Helper Mods (Modrinth / Xaero maven versions)
fabric_jei_version=19.42.0.379-fabric
fabric_xaeros_minimap_version=26.4.2
fabric_xaerolib_version=1.7.1
fabric_easy_model_entities_version=VzSx0phX
fabric_cobblemon_version=1.7.3-fabric
# NeoForge Mod Loader
neoforge_version=21.1.244
# NeoForge Helper Mods (Modrinth / Xaero maven versions)
neoforge_jei_version=19.42.0.379-neoforge
neoforge_xaeros_minimap_version=26.4.2
neoforge_xaerolib_version=1.7.1
neoforge_easy_model_entities_version=mNZXD111
neoforge_epic_fight_version=21.17.3.1-mc1.21.1-neoforge
neoforge_cobblemon_version=1.7.3-neoforge
neoforge_kotlin_for_forge_version=5.12.0
neoforge_architectury_version=13.0.11+neoforge
# Publish to CurseForge
curseforge_release_type=release
curseforge_project_id=1214728
curseforge_api_token=Never put your token here!
# Publish to Modrinth
modrinth_release_type=release
modrinth_project_id=uTGjf7vA
modrinth_api_token=Never put your token here!
